[phases.setup]
aptPkgs = ["git-lfs"]

[phases.build]
cmds = [
    "git lfs install --skip-smudge",
    "git lfs pull",
    "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn run:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120"
